before_script: cd SimMonitor.v5
language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-22

script: ant debug
deploy:
  provider: releases  
  file: '/home/travis/build/jikeloid/U-SIMonitor/SimMonitor.v5/bin/MainActivity-debug.apk'
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: "xTRPJK046Y197tDfDtLPSsY8YejnJnUWib7VC+DA5yCjD0RNnnSpGAx9c+ewvb0R3o1SvQP9fShb/oqgsSqHEeMF1BKuryjbux45liOwgPkx/FA6kv+ciAnLWfUrez5duEj17bXxizGFlAIIO/M7mFTVau+BGUrv3FZXwXmcEoAwtbdjpkoOBqdAfSE7OYZQkEaTh/CpFQw1hvbYzOR39P3/g2UrKtlHjd3GQTEqlFeZYiq/LuH3t5htZz2aakbE60uVRdDJMHhpNFCSryW3Ho/ZFfwIQt2vNnmBglrcrnLZ/gtoVVpeab6oMl1+GBxRfuq4x/EO4jyAe88lKgZkhheOlVUGQ5xUFKEnrQjz6NejdfnJSlV2LccdLxVQ8QWjFE9ace5n7L3FEvVpxWRmb9sEkyvyLIDmm/8ZBo66R9NraEpN6aisNBVtyLvKyFkRUSL6aqZZeWkoyrD/lzoKoxE7/qnkgO1QFEB1wGQ7AfjowEXqpMV75Aa06CTcwWkKy2rxVc94UAng7tFUJfIL3m5MIUig6tmhr9UT0DiP2WaYzij0WJ5KwiN8Jw82WOcmFUzV0USlg8xrqINgXwTMrW/8lqi1C05ZhDMcXeLAu4ohh78IGfrhW/JNN9A3V0qlgx2h7Vat+H67wgwd5PuLRCrLzdHxSIZlz7EMJD9GR9c="
  on:
    tags: true
    all_branches: true
    repo: jikeloid/U-SIMonitor
    
