before_script: cd SimMonitor.v5
language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-22

script: ant debug

env:
  global:
    secure: "x6xEE60T9QBHeBKWCyyhDhF9E0g55MMVBgeaZ4F0Obp6nJddsfgdVDVGfbAk4GDNKm2bsTfsNIhMQ9Ua8LNlzo0YQC5/tuuW9I4vfwf/G/1JW/6TeeX/N5CN8nHeazzUaMF72KtlpeF5fs4w0s2Q5nGdeGM2oBbrw9vd07LG9CjFte9w5F/TOm6jgjo+P924DdKfVyYsuw+C7UyWCou/DRbLAKrQj83DUkjsyJK/6J7S0cyJzBDYO72i260v+SEomth4Jr08y88zWxIrR9gtdpUxNnR1CS78DZ2TEdCymCyiagjAn3uSgXa3JNj6eIFuZIiY/wmkG3mUiQPAhJi8JMCEgxIWguw3p3XeaVMT+G8Js4kRkLWl5/ng4HpKtTNN/62FNZPVExJALq/KE+QUEngtsUiTOv8mHlYy53aQiqzrKTLSHe+uBVBfRv52Olw9UfGkNYl1EXQd5kEC7OMVwq4dshL6lfyE7EZwVAKZuSMfmGDygOUNVLRayWGF03MlNKXzq83dpWn3TH1y89OZ2D2FwvGgZoRPlRQfrENL5Oaxx3mLR+x97ZpW3/mbtsBbwC5GatPhhc9SuFXu5918ZxHvAiIQyRCDCzWJ1Y/2j1yWK43hAvsxivsMR95Sbudou7lz+0IjCxaupWRUxwX2nNDjKPnNteboU8AcokW7xD8="

deploy:
  provider: releases  
  file: 'SimMonitor.v5/bin/MainActivity-debug.apk'
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    all_branches: true
    repo: jikeloid/U-SIMonitor
    
